app/routes/main.py
from flask import Blueprint, render_template, redirect, url_for
import os
from app.utils import render_markdown_with_context
from app.utils import NAVIGATION, full_page_hierarchy


bp = Blueprint('main', __name__)


# Landing page
@bp.route('/')
def index():
    return render_template('landing.html')


@bp.route('/home')
def home():
    return redirect(url_for('main.index'))


# Student page
@bp.route('/student')
def student():
    return render_template('student.html')


# Standalone route (e.g., /create-a-new-study)
@bp.route('/<page_name>')
def show_page(page_name):
    standalone_file_path = os.path.join('markdown_files', f'{page_name}.md')
    if os.path.exists(standalone_file_path):
        # Use render_markdown_with_context to get both the content and YAML data
        content, yaml_data = render_markdown_with_context(standalone_file_path, {})

        # Get the title from YAML if it exists, otherwise fallback to page name
        title = yaml_data.get('name', page_name.replace('_', ' ').capitalize())

        # Build the breadcrumb path using the full_page_hierarchy or fallback to default
        breadcrumb_path = full_page_hierarchy.get(page_name, [{"name": "home", "display": "Home"}])

        return render_template(
            'base.html',
            content=content,
            title=title,
            navigation=NAVIGATION,
            breadcrumb_path=breadcrumb_path
        )
    else:
        return "Page not found", 404

app/routes/manual.py
from flask import Blueprint, render_template
import os
from app.utils import render_markdown_with_context
from app.utils import NAVIGATION, full_page_hierarchy
from app.utils import step_1, step_2

bp = Blueprint('manual', __name__)


@bp.route('/step-<int:step>/<faculty>/<study_type>/<assistant_status>/<page_name>')
def show_step(step, faculty, study_type, assistant_status, page_name):
    """
    Handle both online and lab studies, using the 'assistant_status'
    as a placeholder for online studies (e.g., '/n/').
    """
    file_path = os.path.join('markdown_files', f'{page_name}.md')

    if os.path.exists(file_path):
        # Prepare the context to be passed to the markdown file
        context = {
            'faculty': faculty,
            'study_type': study_type,
            'assistant_status': assistant_status
        }

        content, yaml_data = render_markdown_with_context(file_path, context)
        title = yaml_data.get('name', page_name.replace('_', ' ').capitalize())

        # Dynamically get the step data (step_1, step_2, etc.)
        step_data = {
            1: step_1,
            2: step_2,
        }.get(step)

        if not step_data:
            return "Step not found", 404

        # Construct the key based on faculty, study type, and assistant status
        key = f"{faculty}-{study_type}-{assistant_status}"

        # Check if the page exists for the specific path
        if key not in step_data or page_name not in step_data[key]:
            return "Page not found", 404

        # Get the current, previous, and next steps
        current_index = step_data[key].index(page_name)
        total_steps = len(step_data[key])
        current_step = current_index + 1
        progress = (current_step / total_steps) * 100

        previous_page = step_data[key][current_index - 1] if current_index > 0 else None
        next_page = step_data[key][current_index + 1] if current_index < total_steps - 1 else None

        # Build the breadcrumb path dynamically using the step and page context
        breadcrumb_path = [
            {"name": "home", "display": "Home"},
            {"name": "researcher-overview", "display": "Researcher manual"},
            {"name": f"step-{step}", "display": f"Step {step}"},
            {"name": page_name, "display": title}
        ]

        return render_template(
            'manual.html',
            content=content,
            title=title,
            navigation=NAVIGATION,
            current_step=current_step,
            total_steps=total_steps,
            progress=progress,
            previous_page=previous_page,
            next_page=next_page,
            step=step,
            faculty=faculty,  # Pass the faculty
            study_type=study_type,  # Pass the study type
            assistant_status=assistant_status,  # Pass the assistant status (even if it's 'n' for online)
            breadcrumb_path=breadcrumb_path  # Use the dynamically built breadcrumb path
        )
    else:
        return "Page not found", 404


@bp.route('/researcher-account')
def researcher_account():
    return render_template(
        'researcher_account.html',
        navigation=NAVIGATION,
        breadcrumb_path=full_page_hierarchy.get("account-check", [{"name": "home", "display": "Home"}])
    )


@bp.route('/researcher-overview')
def researcher_overview():
    return render_template(
        'researcher_overview.html',
        navigation=NAVIGATION,
        breadcrumb_path=full_page_hierarchy.get("researcher-overview", [{"name": "home", "display": "Home"}])
    )

app/routes/search.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, session
import os
import json
import logging
import uuid
from app.utils import initialize_model_and_tokenizer, embed_text
from app.services import load_embeddings_metadata, create_faiss_index
import gc
from app.utils import NAVIGATION


# Define a Blueprint for the search functionality
bp = Blueprint('search', __name__)

# Setup logging to record information and errors
logging.basicConfig(level=logging.INFO)

# Initialize the tokenizer and model for embedding text
tokenizer, model, device = initialize_model_and_tokenizer()
logging.info("Model and tokenizer loaded successfully on %s", device)

# Load the embeddings and metadata from files
embeddings, metadata = load_embeddings_metadata()

# Create the FAISS index using the loaded embeddings
index = create_faiss_index(embeddings)

@bp.route('/search', methods=['GET', 'POST'])
def search():
    """
    Handle search requests and return search results.

    This route handles both GET and POST requests to perform a search using the FAISS index.
    It embeds the query text, performs the search, and redirects to the results page.

    :return: A redirect to the results page or a JSON response with an error message.
    """
    try:
        # Get the search query from the request
        query = request.json.get('query') if request.method == 'POST' else request.args.get('query')
        logging.info("Received query: %s", query)

        # Validate the query
        if not isinstance(query, str) or not query.strip():
            logging.error("Invalid input: %s", query)
            return jsonify({"error": "Invalid input"}), 400

        # Embed the query text
        query_embedding = embed_text(query, tokenizer, model, device).reshape(1, -1)
        logging.info("Query embedding created successfully")

        # Perform the search using the FAISS index
        distances, indices = index.search(query_embedding, k=5)
        logging.info("Search completed. Distances: %s, Indices: %s", distances, indices)

        # Retrieve the search results using the indices
        results = [metadata[idx] for idx in indices[0]]
        for result in results:
            result['title'] = result['filename'].replace('.md', '').replace('-', ' ').capitalize()
        logging.info("Search results: %s", results)

        # Generate a unique ID for the search results
        search_id = str(uuid.uuid4())
        search_results_dir = '/tmp/flask_session/'
        search_results_path = os.path.join(search_results_dir, f'{search_id}.json')

        # Ensure the directory exists
        os.makedirs(search_results_dir, exist_ok=True)

        # Save the search results to a file
        with open(search_results_path, 'w', encoding='utf-8') as f:
            json.dump({'query': query, 'results': results}, f)

        # Store the search ID in the session
        session['search_id'] = search_id

        # Redirect to the results page
        return redirect(url_for('search.results_page'))
    except Exception as e:
        logging.error("Error during search: %s", e)
        return jsonify({"error": "An error occurred during the search process"}), 500

@bp.route('/results', methods=['GET'])
def results_page():
    """
    Render the search results page.

    This route handles GET requests to display the search results stored in the session.

    :return: Rendered template of search results or a 404 error message.
    """
    # Retrieve the search ID from the session
    search_id = session.get('search_id')
    if not search_id:
        return "No search results found.", 404

    # Construct the path to the search results file
    search_results_path = os.path.join('/tmp/flask_session/', f'{search_id}.json')
    if not os.path.exists(search_results_path):
        return "Search results file not found.", 404

    # Load the search results from the file
    with open(search_results_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Extract the query and results from the data
    query = data.get('query', '')
    results = data.get('results', [])

    # Render the search results template with navigation and breadcrumbs
    return render_template(
        'search_results.html',
        query=query,
        results=results,
        navigation=NAVIGATION,
        breadcrumb_path=[{"name": "home", "display": "Home"}] 
    )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <!-- Load Bootstrap first -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/8cbbd58934.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nav_pane.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/collapsibles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_content.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/media.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/typography.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}">  
    <link rel="stylesheet" href="{{ url_for('static', filename='css/progress.css') }}">  
    <!-- Page Title and Favicon -->
    <title>VBL</title>
    <link rel="icon" type="ximage/png" href="{{ url_for('static', filename='images/vbl_logo_cropped.png') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Navigation Pane -->
            <div class="col-md-3 nav-pane-container">
                <!-- Logo -->
                <div class="logo-container">
                    <div class="logo-text">VU Behavioural Lab</div>
                    <a href="{{ url_for('main.show_page', page_name='home') }}">
                        <img src="{{ url_for('static', filename='images/vbl_logo_cropped.png') }}" alt="Logo" class="img-fluid vbl-logo">
                    </a>
                </div>
                
                <!-- Search Form -->
                <form id="search-form" class="form-inline my-2 my-lg-0 search-form" onsubmit="event.preventDefault(); performSearch();">
                    <input class="form-control mr-sm-2 search-input" type="search" placeholder="Search" aria-label="Search" name="query" id="search-query">
                    <button class="custom-search-button" type="submit">Search</button> <!-- Updated class here -->
                </form>

                
                <!-- Navigation Pane -->
                <div class="nav-pane">
                    {% for page in navigation %}
                    <a href="{{ url_for('main.show_page', page_name=page.name) }}" class="nav-link">{{ page.display }}</a>
                    {% endfor %}
                </div>

                <div class="university-logo-container">
                    <img src="{{ url_for('static', filename='images/vu_logo.jpg') }}" alt="VU Logo" class="university-logo">
                </div>
                
            </div>

            <!-- Main Content Area -->
            <div class="col-md-9">
                <nav aria-label="breadcrumb" style="font-size: 1rem;">
                    <ol class="breadcrumb">
                      {% for crumb in breadcrumb_path %}
                      <li class="breadcrumb-item">
                        <a href="{{ url_for('main.show_page', page_name=crumb.name) }}">{{ crumb.display }}</a>
                      </li>
                      {% endfor %}
                    </ol>
                </nav>

                <div class="content-container">
                    {% block content %}
                    <!-- The content from markdown files will be rendered inside this block -->
                    {{ content|safe }}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- Optional: Include jQuery if it's not already included -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- My JS -->
    <script src="{{ url_for('static', filename='js/slider.js') }}"></script>
    <script src="{{ url_for('static', filename='js/collapsibles.js') }}"></script>
    <script src="{{ url_for('static', filename='js/preview.js') }}"></script>
    <script>
        function performSearch() {
            const query = document.getElementById('search-query').value;
            console.log('Search function triggered with query: ' + query);
            fetch("{{ url_for('search.search') }}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ query: query })
            })
            .then(response => {
                if (response.ok) {
                    window.location.href = "{{ url_for('search.results_page') }}";
                } else {
                    response.json().then(data => {
                        const container = document.getElementById('search-results-container');
                        container.innerHTML = `<p>${data.error}</p>`;
                    });
                }
            })
            .catch(error => console.error('Error:', error));
        }
    </script> 
</body>
</html>

app/templates/manual.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <!-- Load Bootstrap first -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/8cbbd58934.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nav_pane.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/collapsibles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_content.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/media.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/typography.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/progress.css') }}">  
    <link rel="icon" type="ximage/png" href="{{ url_for('static', filename='images/vbl_logo_cropped.png') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Navigation Pane -->
            <div class="col-md-3 nav-pane-container">
                <!-- Logo -->
                <div class="logo-container">
                    <div class="logo-text">VU Behavioural Lab</div>
                    <a href="{{ url_for('main.show_page', page_name='home') }}">
                        <img src="{{ url_for('static', filename='images/vbl_logo_cropped.png') }}" alt="Logo" class="img-fluid vbl-logo">
                    </a>
                </div>

                <!-- Search Form -->
                <form id="search-form" class="form-inline my-2 my-lg-0 search-form" onsubmit="event.preventDefault(); performSearch();">
                    <input class="form-control mr-sm-2 search-input" type="search" placeholder="Search" aria-label="Search" name="query" id="search-query">
                    <button class="custom-search-button" type="submit">Search</button>
                </form>

                <!-- Navigation Pane -->
                <div class="nav-pane">
                    {% for page in navigation %}
                    <a href="{{ url_for('main.show_page', page_name=page.name) }}" class="nav-link">{{ page.display }}</a>
                    {% endfor %}
                </div>

                <div class="university-logo-container">
                    <img src="{{ url_for('static', filename='images/vu_logo.jpg') }}" alt="University Logo" class="university-logo">
                </div>
            </div>

            <!-- Main Content Area -->
            <div class="col-md-9">
                
                <nav aria-label="progress-bar" style="font-size: 1rem;">
                    <div class="d-flex justify-content-between align-items-center" style="width: 100%; margin: 5px 0;">
                        
                        <!-- Progress Bar -->
                        {% if progress is defined %}
                        <div class="progress" style="width: 80%; height: 30px;">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                                style="width: {{ progress|round(0) }}%; background-color: #007bff;"
                                aria-valuenow="{{ progress|round(0) }}" aria-valuemin="0" aria-valuemax="100">
                                {{ progress|int }}%
                            </div>
                        </div>
                        {% endif %}

                        <!-- Return to Homepage Button -->
                        <a href="{{ url_for('main.show_page', page_name='researcher-overview') }}" class="btn btn-secondary">
                            <i class="fas fa-home"></i> Return to Overview
                        </a>
                        
                    </div>
                </nav>
                                
                <!-- Search Results Content -->
                <div class="content-container mt-4">
                    
                    <!-- Top Navigation Buttons -->
                    <div class="d-flex justify-content-between mt-1" style="margin-bottom: 40px;">
                        {% if previous_page %}
                            <a href="{{ url_for('manual.show_step', step=step, faculty=faculty, study_type=study_type, assistant_status=assistant_status, page_name=previous_page) }}" class="btn btn-outline-primary">Previous</a>
                        {% else %}
                            <span></span>
                        {% endif %}

                        {% if next_page %}
                            <a href="{{ url_for('manual.show_step', step=step, faculty=faculty, study_type=study_type, assistant_status=assistant_status, page_name=next_page) }}" class="btn btn-outline-primary">Next</a>
                        {% else %}
                            <span></span>
                        {% endif %}
                    </div>

                    {{ content|safe }}
                    
                </div>

            </div>
        </div>
    </div>

    <!-- Optional: Include jQuery if it's not already included -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- My JS -->
    <script src="{{ url_for('static', filename='js/slider.js') }}"></script>
    <script src="{{ url_for('static', filename='js/collapsibles.js') }}"></script>
    <script src="{{ url_for('static', filename='js/preview.js') }}"></script>
    <script>
        function performSearch() {
            const query = document.getElementById('search-query').value;
            console.log('Search function triggered with query: ' + query);
            fetch("{{ url_for('search.search') }}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ query: query })
            })
            .then(response => {
                if (response.ok) {
                    window.location.href = "{{ url_for('search.results_page') }}";
                } else {
                    response.json().then(data => {
                        const container = document.getElementById('search-results-container');
                        container.innerHTML = `<p>${data.error}</p>`;
                    });
                }
            })
            .catch(error => console.error('Error:', error));
        }
    </script> 
</body>
</html>

app/templates/search_results.html
{% extends "base.html" %}

{% block content %}
<h2>Search Results for "{{ query }}"</h2>

The pages below are the <b>most likely</b> pages to include information related to the search you just made.
<br><br>

{% if results %}
    <ul>
    {% for result in results %}
        <li>
            <a href="{{ url_for('main.show_page', page_name=result['filename'].replace('.md', '')) }}">
                {{ result['title'] }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No results found.</p>
{% endif %}
{% endblock %}

app/templates/step_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <!-- Load Bootstrap first -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/8cbbd58934.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nav_pane.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/collapsibles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_content.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/media.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/typography.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/progress.css') }}">  
    <link rel="icon" type="ximage/png" href="{{ url_for('static', filename='images/vbl_logo_cropped.png') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Navigation Pane -->
            <div class="col-md-3 nav-pane-container">
                <!-- Logo -->
                <div class="logo-container">
                    <div class="logo-text">VU Behavioural Lab</div>
                    <a href="{{ url_for('main.show_page', page_name='home') }}">
                        <img src="{{ url_for('static', filename='images/vbl_logo_cropped.png') }}" alt="Logo" class="img-fluid vbl-logo">
                    </a>
                </div>

                <!-- Search Form -->
                <form id="search-form" class="form-inline my-2 my-lg-0 search-form" onsubmit="event.preventDefault(); performSearch();">
                    <input class="form-control mr-sm-2 search-input" type="search" placeholder="Search" aria-label="Search" name="query" id="search-query">
                    <button class="custom-search-button" type="submit">Search</button>
                </form>

                <!-- Navigation Pane -->
                <div class="nav-pane">
                    {% for page in navigation %}
                    <a href="{{ url_for('main.show_page', page_name=page.name) }}" class="nav-link">{{ page.display }}</a>
                    {% endfor %}
                </div>

                <div class="university-logo-container">
                    <img src="{{ url_for('static', filename='images/vu_logo.png') }}" alt="University Logo" class="university-logo">
                </div>
            </div>

            <!-- Main Content Area -->
            <div class="col-md-9">
                <nav aria-label="breadcrumb" style="font-size: 1rem;">
                    <ol class="breadcrumb">
                      {% for crumb in breadcrumb_path %}
                      <li class="breadcrumb-item">
                        <a href="{{ url_for('main.show_page', page_name=crumb.name) }}">{{ crumb.display }}</a>
                      </li>
                      {% endfor %}
                    </ol>
                </nav>

                <nav aria-label="progress-bar" style="font-size: 1rem;">
                    <div class="d-flex justify-content-between align-items-center" style="width: 100%; margin: 20px 0;">
                        
                        
                        <!-- Progress Bar -->
                        {% if progress is defined %}
                        <div class="progress" style="width: 80%; height: 30px;">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                                style="width: {{ progress|round(0) }}%; background-color: #007bff;"
                                aria-valuenow="{{ progress|round(0) }}" aria-valuemin="0" aria-valuemax="100">
                                {{ progress|int }}%
                            </div>
                        </div>
                        {% endif %}

                        <!-- Return to Homepage Button -->
                        <a href="{{ url_for('main.show_page', page_name='researcher-overview') }}" class="btn btn-secondary">
                            <i class="fas fa-home"></i> Return to Overview
                        </a>
                        
                    </div>
                </nav>
                                
                <!-- Search Results Content -->
                <div class="content-container mt-4">
                    
                    <!-- Top Navigation Buttons -->
                    <div class="d-flex justify-content-between mt-1" style="margin-bottom: 40px;">
                        {% if previous_page %}
                            <a href="{{ url_for('main.show_step', step=step, faculty=faculty, study_type=study_type, assistant_status=assistant_status, page_name=previous_page) }}" class="btn btn-outline-primary">Previous</a>
                        {% else %}
                            <span></span>
                        {% endif %}

                        {% if next_page %}
                            <a href="{{ url_for('main.show_step', step=step, faculty=faculty, study_type=study_type, assistant_status=assistant_status, page_name=next_page) }}" class="btn btn-outline-primary">Next</a>
                        {% else %}
                            <span></span>
                        {% endif %}
                    </div>

                    {{ content|safe }}
                    
                </div>

            </div>
        </div>
    </div>

    <!-- Optional: Include jQuery if it's not already included -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- My JS -->
    <script src="{{ url_for('static', filename='js/slider.js') }}"></script>
    <script src="{{ url_for('static', filename='js/collapsibles.js') }}"></script>
    <script src="{{ url_for('static', filename='js/preview.js') }}"></script>
    <script>
        function performSearch() {
            const query = document.getElementById('search-query').value;
            console.log('Search function triggered with query: ' + query);
            fetch("{{ url_for('search.search') }}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ query: query })
            })
            .then(response => {
                if (response.ok) {
                    window.location.href = "{{ url_for('search.results_page') }}";
                } else {
                    response.json().then(data => {
                        const container = document.getElementById('search-results-container');
                        container.innerHTML = `<p>${data.error}</p>`;
                    });
                }
            })
            .catch(error => console.error('Error:', error));
        }
    </script> 
</body>
</html>